server:
  port: ${SPRING_SERVER_PORT:8085}
spring:
  banner:
    image:
      location:
        /images/banner.png
proxy:
  selenium:
    container:
      name: hlm-selenium-standalone-xpra
    port: 4444
  healenium:
    container:
      name: healenium
    report:
      path: /healenium/report/