server:
  port: ${SPRING_SERVER_PORT:8085}
spring:
  banner:
    image:
      location:
        /images/banner.png
proxy:
  protocol: http
  new:
    session:
      path: /wd/hub/session
  selenium:
    container:
      name: hlm-selenium-standalone-xpra
    executor:
      path: /wd/hub
  healenium:
    container:
      name: healenium
    report:
      path: /healenium/report/