server:
  port: ${SPRING_SERVER_PORT:8085}
spring:
  banner:
    image:
      location:
        /images/banner.png
proxy:
  selenium:
    url: http://${SELENIUM_HOST:localhost}:${SELENIUM_PORT:4444}${SELENIUM_URL:/wd/hub}
  appium:
    url: http://${APPIUM_HOST:localhost}:${APPIUM_PORT:4723}/wd/hub
  healenium:
    container:
      url: http://${HEALENIUM_HOST:localhost}:${HEALENIUM_PORT:7878}
    report:
      url: http://${SERVER_HOST:localhost}:${SERVER_PORT:7878}/healenium/report/
  imitate:
    container:
      url: http://${IMITATE_HOST:localhost}:${IMITATE_PORT:8000}
healing:
  healenabled: ${HEAL_ENABLED:true}
  recoverytries: ${RECOVERY_TRIES:1}
  scorecap: ${SCORE_CAP:.6}